# Generated by Django 4.0.5 on 2022-08-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafelist',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='cafelist',
            name='description',
            field=models.TextField(db_index=True),
        ),
    ]
