# Generated by Django 4.0.5 on 2022-09-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_rename_name_cafelist_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafelist',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
