# Generated by Django 4.0.5 on 2022-09-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_alter_cafelist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafelist',
            name='slug',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
