# Generated by Django 4.1.1 on 2023-03-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0004_alter_cafelist_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('description', models.TextField(db_index=True)),
                ('image', models.ImageField(upload_to='static/images/cafes')),
            ],
        ),
        migrations.DeleteModel(
            name='CafeList',
        ),
    ]
