# Generated by Django 4.1.1 on 2023-03-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0005_cafe_delete_cafelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
