# Generated by Django 4.1.1 on 2023-03-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0006_alter_cafe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='slug',
        ),
        migrations.AlterField(
            model_name='cafe',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='image',
            field=models.ImageField(upload_to='static/images/cafes/cafe_images'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='CafeMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredients', models.TextField()),
                ('image', models.ImageField(upload_to='static/images/cafes/delicious_images')),
                ('id_cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.cafe')),
            ],
        ),
    ]
