# Generated by Django 4.1.1 on 2023-03-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0009_cafemenu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='category',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='cafemenu',
            name='category',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='cafemenu',
            name='name',
            field=models.CharField(db_index=True, max_length=75, unique=True),
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
