# Generated by Django 4.1.1 on 2023-03-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0012_cafemenu_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafemenu',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
