# Generated by Django 4.1.1 on 2023-03-24 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0017_alter_cafe_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='CafeMenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=75)),
            ],
        ),
        migrations.AlterField(
            model_name='cafe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cafes.cafecategory'),
        ),
        migrations.AlterField(
            model_name='cafemenu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cafes.cafemenucategory'),
        ),
    ]
