# Generated by Django 4.1.1 on 2023-03-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0018_cafecategory_cafemenucategory_alter_cafe_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafecategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cafemenucategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
