# Generated by Django 4.1.1 on 2023-03-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0020_alter_cafecategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafecategory',
            name='name',
            field=models.CharField(choices=[('1', 'Кафе'), ('2', 'Ресторан'), ('3', 'Пиццерия'), ('4', 'Азиатская кухня'), ('5', 'ФастФуд')], max_length=75, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cafemenucategory',
            name='name',
            field=models.CharField(choices=[('1', 'Бургеры'), ('2', 'Пицца'), ('3', 'Роллы'), ('4', 'Закуски'), ('5', 'Десерты'), ('6', 'Напитки')], default=2, max_length=75, unique=True),
            preserve_default=False,
        ),
    ]
