# Generated by Django 4.1.1 on 2023-03-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0021_cafecategory_name_cafemenucategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafecategory',
            name='name',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
