# Generated by Django 4.1.1 on 2023-03-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0023_remove_cafecategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cafecategory',
            name='category',
            field=models.CharField(choices=[('Cafe', 'Кафе'), ('Restoraunt', 'Ресторан'), ('Pizzaria', 'Пиццерия'), ('AsianFood', 'Азиатская кухня'), ('FastFood', 'ФастФуд')], max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='cafemenucategory',
            name='category',
            field=models.CharField(choices=[('Burger', 'Бургеры'), ('Pizza', 'Пицца'), ('Rolls', 'Роллы'), ('Snack', 'Закуски'), ('Deserts', 'Десерты'), ('Drinks', 'Напитки')], max_length=75, unique=True),
        ),
    ]
