# Generated by Django 4.1.1 on 2023-03-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0024_cafe_location_alter_cafecategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='location',
            field=models.CharField(max_length=1000),
        ),
    ]
