# Generated by Django 4.1.1 on 2023-03-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0025_alter_cafe_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafecategory',
            name='category',
            field=models.CharField(choices=[('Кафе', 'Кафе'), ('Рестораны', 'Ресторан'), ('Пиццерии', 'Пиццерия'), ('Азиатская кухня', 'Азиатская кухня'), ('Фастфуд', 'ФастФуд')], max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='cafemenucategory',
            name='category',
            field=models.CharField(choices=[('Бургеры', 'Бургеры'), ('Пицца', 'Пицца'), ('Роллы', 'Роллы'), ('Закуски', 'Закуски'), ('Десерты', 'Десерты'), ('Напитки', 'Напитки')], max_length=75, unique=True),
        ),
    ]
