# Generated by Django 4.1.1 on 2023-02-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/images/main/default_logo_user.jpg', upload_to='static/images/users/avatars'),
        ),
    ]
