# Generated by Django 4.1.1 on 2023-03-20 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0010_cafe_category_cafemenu_category_alter_cafemenu_name_and_more'),
        ('main', '0009_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('id_cafe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafes.cafe')),
                ('id_dishes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafes.cafemenu')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
