# Generated by Django 4.1.1 on 2023-03-20 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
