# Generated by Django 4.1.1 on 2023-03-25 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0024_cafe_location_alter_cafecategory_category_and_more'),
        ('main', '0011_delete_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=75)),
                ('comment', models.TextField()),
                ('mark', models.CharField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Нормально'), (2, 'Плохо'), (1, 'Ужасно')], max_length=10)),
                ('public_date', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.cafe')),
            ],
        ),
    ]
