# Generated by Django 4.1.1 on 2023-03-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_commentcafe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentcafe',
            name='mark',
        ),
        migrations.AlterField(
            model_name='commentcafe',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
