# Generated by Django 4.1.1 on 2023-03-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_commentcafe_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcafe',
            name='mark',
            field=models.CharField(choices=[('5', 'Отлично'), ('4', 'Хорошо'), ('3', 'Нормально'), ('2', 'Плохо'), ('1', 'Ужасно')], max_length=10, null=True),
        ),
    ]
