# Generated by Django 4.1.1 on 2023-03-26 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafes', '0027_alter_cafecategory_category'),
        ('orders', '0002_alter_itemsinorder_cafe_alter_itemsinorder_dish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsinorder',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cafes.cafe'),
        ),
        migrations.AlterField(
            model_name='itemsinorder',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cafes.cafemenu'),
        ),
        migrations.AlterField(
            model_name='itemsinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
